### ISSUE TITLE
Density output

### ISSUE THREAD

**Issue by hollyallen8** [bdavis222/dotscanner#8]
It isn't that clear how the density output is calculated. It says density /um2, but other users might not be doing it using those units. I think it would be better to also give the output of the total number of dots, and area in px2 in addition to the 'density' so that the user can check that the scale factor is correct.

**Comment by bdavis222** [comment]
The default units are "per sq pix", and this will only change to "per sq um" if the user explicitly enters a scale factor (in um/pix) in the config file. The default value of None will run the calculation in pixels rather than microns, and the output file does reflect that. Please update this bug if you are seeing something different.
